CREATE TABLE ADDRESSES
(
    ID NUMBER PRIMARY KEY,
    HOTEL_ID NUMBER,
    TYPE NUMBER,
    COUNTRY NUMBER,
    REGION VARCHAR2(1000),
    DISTRICT VARCHAR2(1000),
    SETTLEMENT VARCHAR2(1000),
    BUILDING VARCHAR2(100),
    FLAT VARCHAR2(100),
    CREATED_AT DATE,
    CHANGED_AT DATE
)